#!/usr/bin/env bash

if [ "${TRAVIS_BRANCH}" == 'master' ] && [ "${TRAVIS_PULL_REQUEST}" == 'false' ]; then
  echo "===== Starting Deployment... ====="
  mvn deploy --settings ci/deploy_settings.xml
else
  echo "===== No deployment is done ====="
fi
